name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Backend Tests
      run: |
        dotnet test src/backend/SnackSpotAuckland.Tests/SnackSpotAuckland.Tests.csproj --verbosity minimal
    
    - name: Frontend Tests
      run: |
        cd src/frontend
        npm ci
        npm run lint
        npm run build