name: Security Scanning

on:
  schedule:
    - cron: '0 2 * * 1' # Run every Monday at 2 AM
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    
    - name: .NET Security Scan
      run: |
        cd src/backend/SnackSpotAuckland.Api
        dotnet list package --vulnerable --include-transitive || true
        dotnet list package --outdated || true
    
    - name: npm Security Scan
      run: |
        cd src/frontend
        npm audit --audit-level=high || true
        npm outdated || true
    
    - name: CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: csharp, javascript
    
    - name: Build for CodeQL
      run: |
        cd src/backend/SnackSpotAuckland.Api && dotnet build
        cd ../../../src/frontend && npm ci && npm run build
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  # container-scan:
  #   name: Container Security Scan
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - uses: actions/checkout@v4
  #   
  #   - name: Build Docker image
  #     run: |
  #       # Add Docker build commands when containers are implemented
  #       echo "Container scanning will be added when Docker images are implemented"
  #   
  #   - name: Run Trivy vulnerability scanner
  #     uses: aquasecurity/trivy-action@master
  #     with:
  #       image-ref: 'snackspot:latest'
  #       format: 'sarif'
  #       output: 'trivy-results.sarif'
  #     continue-on-error: true
  #   
  #   - name: Upload Trivy scan results
  #     uses: github/codeql-action/upload-sarif@v3
  #     with:
  #       sarif_file: 'trivy-results.sarif'
  #     continue-on-error: true