name: Security Scanning

on:
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Backend Security Check
      run: |
        cd src/backend/SnackSpotAuckland.Api
        dotnet list package --vulnerable --include-transitive
      continue-on-error: true
    
    - name: Frontend Security Check
      run: |
        cd src/frontend
        npm audit --audit-level=high
      continue-on-error: true